name: Build & Push

on:
  push:
    branches: [ main ]
    tags:

env:
  NAME: website
  DO_REGISTRY_URL: registry.digitalocean.com/modulusrebus-images

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          yarn
          yarn build
          docker build -t $DO_REGISTRY_URL/$NAME:latest .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push latest
        run: docker push $DO_REGISTRY_URL/$NAME:latest

      - name: Push tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag \
            $DO_REGISTRY_URL/$NAME:latest \
            $DO_REGISTRY_URL/$NAME:${{ github.ref_name }}
          docker push \
            $DO_REGISTRY_URL/$NAME:${{ github.ref_name }}
